set :user, "lukasz"
set :domain, "#{user}@lukaszbadura.com"
set :application, "lukaszbadura.com"
set :repository, "git@github.com:lbadura/lukaszbadura.com.git"
set :user, "lukasz"
set :ssh_flags, "-p 22000"
set :deploy_to, "~/sites/#{application}"
